import re

# CALLBACK COMMANDS
CALLBACK_COMMAND_CLOSE = "$close"
CALLBACK_COMMAND_REFRESH_PLAYER = "$refresh_player"
CALLBACK_COMMAND_UPDATE_PLAYER = "$update_player"

ESCAPED_CALLBACK_COMMAND_CLOSE = re.escape(CALLBACK_COMMAND_CLOSE)
