# SECTION NAME ===============================================================
# PLAYER
PLAYER_SECTION_NAME = "JOGADOR"
SIGNUP_SECTION_NAME = "🟢CADASTRADO🟢"
FAIL_SIGNUP_SECTION_NAME = "❗️CADASTRO‼️"
REFRESH_PLAYER_SECTION_NAME = "JOGADOR RECARREGADO"
UPDATE_PLAYER_SECTION_NAME = "JOGADOR ATUALIZADO"
FAIL_UPDATE_PLAYER_SECTION_NAME = "❗️ATUALIZAR JOGADOR‼️"

# GROUP
GROUP_SECTION_NAME = "GRUPO"
SIGNUP_GROUP_SECTION_NAME = "🟢GRUPO CADASTRADO🟢"
FAIL_SIGNUP_GROUP_SECTION_NAME = "❗️CADASTRO GRUPO‼️"
REFRESH_GROUP_SECTION_NAME = "GRUPO RECARREGADO"
UPDATE_GROUP_SECTION_NAME = "GRUPO ATUALIZADO"
FAIL_UPDATE_GROUP_SECTION_NAME = "❗️ATUALIZAR GRUPO‼️"

# WORLD
WORLD_SECTION_NAME = "MUNDO"
FAIL_SHOW_WORLD_SECTION_NAME = "❗️MOSTRAR MUNDO‼️"
FAIL_SIGNUP_WORLD_SECTION_NAME = "❗️CADASTRO MUNDO‼️"

# CITY
FAIL_PUT_CITY_SECTION_NAME = "❗️CRIAR MUNDO‼️"

# SUBSECTION NAME ============================================================
PLAYER_SUBSECTION_NAME = "Jogador"
GROUP_SUBSECTION_NAME = "Grupo"
WORLD_SUBSECTION_NAME = "Mundo"
