# SECTION NAME ===============================================================
# PLAYER
PLAYER_SECTION_NAME = "JOGADOR"
REFRESH_PLAYER_SECTION_NAME = "JOGADOR RECARREGADO"
UPDATE_PLAYER_SECTION_NAME = "JOGADOR ATUALIZADO"
FAIL_UPDATE_PLAYER_SECTION_NAME = "❗️ATUALIZAR JOGADOR‼️"
SIGNUP_SECTION_NAME = "🟢CADASTRADO🟢"
FAIL_SIGNUP_SECTION_NAME = "❗️CADASTRO‼️"

# GROUP
SIGNUP_GROUP_SECTION_NAME = "🟢GRUPO CADASTRADO🟢"
FAIL_SIGNUP_GROUP_SECTION_NAME = "❗️CADASTRO GRUPO‼️"

# SUBSECTION NAME ============================================================
PLAYER_SUBSECTION_NAME = "Jogador"
GROUP_SUBSECTION_NAME = "Grupo"
