# SECTION NAME ===============================================================
PLAYER_SECTION_NAME = "JOGADOR"
REFRESH_PLAYER_SECTION_NAME = "JOGADOR RECARREGADO"
UPDATE_PLAYER_SECTION_NAME = "JOGADOR ATUALIZADO"
SIGNUP_SECTION_NAME = "CADASTRO"
SIGNUP_GROUP_SECTION_NAME = "CADASTRO GRUPO"

# SUBSECTION NAME ============================================================
PLAYER_SUBSECTION_NAME = "Jogador"
GROUP_SUBSECTION_NAME = "Grupo"
